#!/bin/bash

echo "What is your name?"
read name

echo "What is your age?"
read age

echo "What is your college name?"
read college

echo "My name is $name"
echo "My age is $age"
echo "My college name is $college"
